version: '3.8'

services:
  web:
    build: ./Backend
    command: sh -c "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./Backend/:/usr/src/Backend/
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - lms-network
  db:
    ports:
      - "5422:5432"
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=islam2002
      - POSTGRES_DB=web_lms_db
    networks:
      - lms-network

volumes:
  postgres_data:

networks:
  lms-network:
    driver: bridge