# Generated by Django 4.1.7 on 2023-02-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_category_alter_course_title_course_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_name',
            new_name='category_name',
        ),
    ]
