# Generated by Django 4.1.7 on 2023-02-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
