# Generated by Django 4.1.7 on 2023-02-18 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_course_discount_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
