# Generated by Django 4.1.7 on 2023-02-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount',
            field=models.IntegerField(default=10, verbose_name='Скидка: '),
        ),
    ]
