# Generated by Django 4.1.7 on 2023-02-19 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_course_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_time',
        ),
        migrations.AddField(
            model_name='course',
            name='end_day',
            field=models.DateField(default=datetime.date(2023, 2, 20)),
        ),
        migrations.AddField(
            model_name='course',
            name='start_day',
            field=models.DateField(default=datetime.date(2023, 2, 19)),
        ),
    ]
