# Generated by Django 4.1.7 on 2023-02-21 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_remove_course_end_time_remove_course_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='discount_confirmation',
            field=models.BooleanField(default=False, verbose_name='Начать акцию'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_day',
            field=models.DateField(default=datetime.date(2023, 2, 22), verbose_name='День окончания скидок: '),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=10000, verbose_name='Цена кусра: '),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_day',
            field=models.DateField(default=datetime.date(2023, 2, 21), verbose_name='День старта скидок: '),
        ),
    ]
