# Generated by Django 4.1.7 on 2023-03-01 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_alter_course_discount_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_day',
            field=models.DateField(default=datetime.date(2023, 3, 2), verbose_name='День окончания скидок: '),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_day',
            field=models.DateField(default=datetime.date(2023, 3, 1), verbose_name='День старта скидок: '),
        ),
    ]
