# Generated by Django 4.1.7 on 2023-03-10 10:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_alter_course_end_day_alter_course_start_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lms.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_day',
            field=models.DateField(default=datetime.date(2023, 3, 11), verbose_name='День окончания скидок: '),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_day',
            field=models.DateField(default=datetime.date(2023, 3, 10), verbose_name='День старта скидок: '),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
