# Generated by Django 4.1.7 on 2023-03-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_alter_course_category_alter_course_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(verbose_name='Цена кусра: '),
        ),
    ]
