# Generated by Django 4.1.7 on 2023-04-13 10:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0026_remove_userprofile_courses_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Course',
            new_name='UserCourse',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
