# Generated by Django 4.1.7 on 2023-04-13 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0027_rename_user_course_usercourse_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='course_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_id', to='lms.course'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
