# Generated by Django 4.1.7 on 2023-04-13 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0030_remove_usercourse_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course'),
        ),
    ]
